# Generated by Django 5.2.9 on 2025-12-16 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutant_code', models.CharField(max_length=100, unique=True, verbose_name='突变体编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '种质/突变体',
                'verbose_name_plural': '种质/突变体',
                'db_table': 'ccge_mutants',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='实验名称')),
                ('year', models.IntegerField(verbose_name='实验年份')),
                ('experiment_type', models.CharField(choices=[('plant', '植物/作物'), ('animal', '动物/家畜')], default='plant', max_length=20, verbose_name='实验类型')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='实验地点')),
                ('description', models.TextField(blank=True, null=True, verbose_name='实验描述')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], default='ongoing', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者姓名')),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实验',
                'verbose_name_plural': '实验',
                'db_table': 'pt_experiments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['year', 'location'], name='pt_experime_year_e0e2ef_idx'), models.Index(fields=['status'], name='pt_experime_status_f7e570_idx')],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ear_tag', models.CharField(max_length=100, unique=True, verbose_name='耳号/RFID')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='栋/舍')),
                ('pen', models.CharField(blank=True, max_length=100, null=True, verbose_name='栏位号')),
                ('sex', models.CharField(choices=[('M', '公'), ('F', '母'), ('C', '阉公')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('birth_weight', models.FloatField(blank=True, null=True, verbose_name='出生重(kg)')),
                ('sire_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='父本耳号')),
                ('dam_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='母本耳号')),
                ('status', models.CharField(choices=[('active', '存栏'), ('dead', '死亡'), ('sold', '出售/淘汰'), ('transferred', '转出')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='phenotype.experiment')),
            ],
            options={
                'verbose_name': '动物个体',
                'verbose_name_plural': '动物个体',
                'db_table': 'pt_animals',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(max_length=50, verbose_name='小区编号')),
                ('mutant_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='突变体编码(快照)')),
                ('status', models.CharField(choices=[('not_collected', '未采集'), ('collected', '已采集'), ('submitted', '已提交')], default='not_collected', max_length=20, verbose_name='采集状态')),
                ('last_collected', models.DateTimeField(blank=True, null=True, verbose_name='最后采集时间')),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('description', models.TextField(blank=True, null=True, verbose_name='种植描述')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='phenotype.experiment', verbose_name='所属试验')),
                ('mutant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='phenotype.mutant', verbose_name='关联种质')),
            ],
            options={
                'verbose_name': '小区',
                'verbose_name_plural': '小区列表',
                'db_table': 'pt_fields',
                'ordering': ['field_code'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='phenotype_media/%Y/%m/', verbose_name='文件路径')),
                ('media_type', models.CharField(choices=[('image', '照片'), ('video', '视频')], default='image', max_length=20, verbose_name='媒体类型')),
                ('capture_time', models.DateTimeField(verbose_name='拍摄时间')),
                ('captured_by', models.CharField(max_length=100, verbose_name='拍摄者')),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('animal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='phenotype.animal', verbose_name='关联动物')),
                ('field_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='phenotype.field', verbose_name='关联小区')),
            ],
            options={
                'verbose_name': '多媒体文件',
                'verbose_name_plural': '多媒体文件',
                'db_table': 'pt_media_files',
            },
        ),
        migrations.CreateModel(
            name='TraitDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='性状名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='性状代码')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('data_type', models.CharField(choices=[('number', '数值型'), ('text', '文本型'), ('category', '选项型'), ('date', '日期型')], default='number', max_length=20, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '性状定义',
                'verbose_name_plural': '性状定义',
                'db_table': 'pt_trait_definitions',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='pt_trait_de_code_dd4360_idx')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500, verbose_name='测量值')),
                ('observer', models.CharField(max_length=100, verbose_name='采集人')),
                ('measure_date', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('is_invisible', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('animal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='phenotype.animal', verbose_name='关联动物')),
                ('field_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='phenotype.field', verbose_name='关联小区')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='phenotype.traitdefinition', verbose_name='性状')),
            ],
            options={
                'verbose_name': '观测数据',
                'verbose_name_plural': '观测数据',
                'db_table': 'pt_observations',
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['ear_tag'], name='pt_animals_ear_tag_738d56_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['experiment', 'pen'], name='pt_animals_experim_abda22_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['field_link'], name='pt_media_fi_field_l_b58ace_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['animal_link'], name='pt_media_fi_animal__76a1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['capture_time'], name='pt_media_fi_capture_7b9acb_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['experiment', 'field_code'], name='pt_fields_experim_b20d77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('experiment', 'field_code')},
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['field_link', 'trait'], name='pt_observat_field_l_a7f234_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['animal_link', 'trait'], name='pt_observat_animal__469325_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['measure_date'], name='pt_observat_measure_cf74ca_idx'),
        ),
    ]
